commonfields:
  id: 366ad0e1-2f75-4add-84ee-e1bb2c0592bf
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.9.9.25564
engineinfo: {}
mainengineinfo: {}
name: test_automation
pswd: ""
runas: DBotWeakRole
runonce: false
script: ""
scripttarget: 0
tags: []
type: python
